version: '3.8'

services:
  web:
    build: .
    command: sh -c "gunicorn runner:app --workers=4 --bind=0.0.0.0:5000 && alembic upgrade head"
    volumes:
      - .:/WhatsApAIBot
    ports:
      - "5000:5000"
    depends_on:
      - redis
      - db
    env_file:
      - .env
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - "5432:5432"

  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    env_file:
      - .env
    restart: on-failure

  celery_worker:
    build: .
    command: celery -A runner.celery worker  --loglevel=info
    depends_on:
      - redis

volumes:
  postgres_data:
  redis-data:
